version: '3'
services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - app
    depends_on:
      - app
      - database
  app:
    image: hsc-local
    build: ./
    restart: always
    volumes:
      - ./app:/var/HSC/app
      - ./node_modules:/var/HSC/node_modules
      - ./public:/var/HSC/public
      - ./themes:/var/HSC/themes
    environment:
      PHP__display_errors: 'On'
      PHP__log_errors: 'On'
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  db-data: