version: '3'
services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/HSC
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
    depends_on:
      - php
      - database
  php:
    image: nanoninja/php-fpm
    restart: always
    volumes:
      - ./:/HSC
    environment:
      PHP__display_errors: 'On'
      PHP__opcache.enable: 'On'
      PHP__memory_limit:   '256M'
      PHP__post_max_size:  '50M'
      PHP__date.timezone:  '"Europe/London"'
      PHP__pm.max_children: '10'
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  db-data: