---
Name: HSC
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - HSC\SiteConfigExtension
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding_providers:
      - HSC\Talks\Talk
      - HSC\Talks\Author
      - HSC\Talks\Series
SilverStripe\GraphQL\Auth\Handler:
  authenticators:
    - class: HSC\Talks\Authenticator
      priority: 50