---
Name: HSC
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - HSC\SiteConfigExtension
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding_providers:
      - HSC\Podcasts\Podcast
      - HSC\Podcasts\Author
      - HSC\Podcasts\Series
SilverStripe\GraphQL\Auth\Handler:
  authenticators:
    - class: HSC\Podcasts\Authenticator
      priority: 10